# Python support can be specified down to the minor or micro version
# (e.g. 3.6 or 3.6.3).
# OS Support also exists for jessie & stretch (slim and full).
# See https://hub.docker.com/r/library/python/ for all supported Python
# tags from Docker Hub.
FROM tiangolo/uwsgi-nginx:python3.7-alpine3.7

# If you prefer miniconda:
#FROM continuumio/miniconda3

ENV LISTEN_PORT=8000
EXPOSE 8000

ENV UWSGI_INI uwsgi.ini

ENV STATIC_URL /static

WORKDIR /mysite
ADD . /mysite

# Using pip:
RUN python3 -m pip install -r requirements.txt
CMD ["python3", "-m", "django"]

# Using pipenv:
#RUN python3 -m pip install pipenv
#RUN pipenv install --ignore-pipfile
#CMD ["pipenv", "run", "python3", "-m", "django"]

# Using miniconda (make sure to replace 'myenv' w/ your environment name):
#RUN conda env create -f environment.yml
#CMD /bin/bash -c "source activate myenv && python3 -m django"
